### ISSUE TITLE
Color Stools

### ISSUE THREAD

**Issue by Mushykins** [APICO-Modders/APICO-Community-Decorations#16]
Wooden Color Stools: [ColorStools.zip](https://github.com/APICO-Modders/APICO-Community-Decorations/files/8767208/ColorStools.zip)

Metal Color Stools[ColorMetalStools.zip](https://github.com/APICO-Modders/APICO-Community-Decorations/files/8767300/ColorMetalStools.zip)

**Comment by Mushykins** [comment]
Added Metal Color Stools as well

**Comment by bCubed3** [comment]
Added both types of stools !
