### ISSUE TITLE
Crafting and Flower Storage, end game infinite storages

### ISSUE THREAD

**Issue by KelpTheShark** [APICO-Modders/APICO-Community-Decorations#27]
I do not have art for this.

Looking for two mid to end game storage systems, like the bee storage that can hold infinite bees of any type.

One would be for flowers and flower seeds, and be able to hold an unlimited amount of each type of seed/flower.

The other would be for crafting materials, like logs, planks, honeycomb, etc. It would also be able to hold an unlimited amount of each crafting material type. Having this open would make the insides accessible to the crafting table.

I'm 100% ok with locking these behind bee type collected and money restraints, or insane crafting requirements. I just hate opening all my chests so I can access them for crafting.

**Comment by bCubed3** [comment]
Hey Kelp, while these are great ideas, I don't think they really fit the theme of the community decorations mod. We're more focused on things that don't actually affect gameplay all that much. You could ask the discord #modding=chat if anyone there is interested in adding these, or you could use the resources there to a mod yourself !

**Comment by KelpTheShark** [comment]
No problem! I ended up finding someone to work on it for me, came here to close this anyway.
