### ISSUE TITLE
Lamp

### ISSUE THREAD

**Issue by ThePebblemancer** [APICO-Modders/APICO-Community-Decorations#3]
![lamp](https://user-images.githubusercontent.com/16887750/169719832-6d5db711-f460-4328-8005-fea6df9934a8.png)

**Comment by Vildravn** [comment]
This sprite is too big :( Please leave a space for the 1px white outline in your sprite (So it should be 14x14 at most)

**Comment by Vildravn** [comment]
Closing in favor of #6
