### ISSUE TITLE
Flowering bush in a pot

### ISSUE THREAD

**Issue by ThePebblemancer** [APICO-Modders/APICO-Community-Decorations#5]
![flowering-bush](https://user-images.githubusercontent.com/16887750/169721048-10402e68-c77f-4bea-9fe3-c1c9a32a0c83.png)

**Comment by Vildravn** [comment]
This sprite is too big :( Please leave a space for the 1px white outline in your sprite (So it should be 14x14 at most)

**Comment by Vildravn** [comment]
Closing in favor of #7
