### ISSUE TITLE
Colored Tables

### ISSUE THREAD

**Issue by Mushykins** [APICO-Modders/APICO-Community-Decorations#9]
Colored Tables. Bee, Check, Diamond, Dotted, Plain, and Polka
[ColoredTables.zip](https://github.com/APICO-Modders/APICO-Community-Decorations/files/8758420/ColoredTables.zip)

**Comment by Vildravn** [comment]
Added all the table variants, we have so many now.

**Comment by Vildravn** [comment]
the colored tables are hereby done, @Mushykins if you want to make updates, please make a new issue, thanks! :)
